### ISSUE TITLE
Permit time-1.6

### ISSUE THREAD

**Issue by ndmitchell** [jystic/unix-compat#19]
GHC 8.0 RC2 ships with time-1.6. unix-compat requires < 1.6. Can you please release a version which permits time-1.6, either by bumping the upper bounds or removing them entirely.

**Comment by jystic** [comment]
I've edited the package metadata on [hackage](http://hackage.haskell.org/package/unix-compat-0.4.1.4) and committed the equivalent to master to make sure it doesn't regress.

**Comment by ndmitchell** [comment]
Thanks!
