### ISSUE TITLE
createLink for windows

### ISSUE THREAD

**Issue by joeyh** [jystic/unix-compat#20]
Turns out that windows supports something that seems identical to unix hard links. Win32-extras System.Win32.HardLink.createHardLink exposes this functionality. 

unix-compat's getFileStatus reports the right link count for hard linked files on windows.

So, suggest making System.PosixCompat.Files.createLink call createHardLink on windows, instead of throwing an error as it does now.

**Comment by jystic** [comment]
I'd be happy enough to add this / accept a PR if people think it's a good idea.

/cc @snoyberg @ndmitchell do you have any thoughts on this?

**Comment by ndmitchell** [comment]
No ideas, I'm afraid.

**Comment by jystic** [comment]
@joeyh if you submit a PR and test that it works I'll be happy to merge it
